# yaml-language-server: $schema=./assets/schema/site.json

siteTitle:
  default: NanoSite
  en: NanoSite
  ja: "ナノサイト"
  zh: "微站"

siteSubtitle:
  default: "Just Markdown. Just a website."
  en: "Just Markdown. Just a website."
  ja: "書くだけ、Markdown。それがサイトになる。"
  zh: "写下 Markdown，就是你的网站。"

siteDescription:
  default: "NanoSite - Just Markdown. Just a website."
  en: "NanoSite - Just Markdown. Just a website."
  ja: "ナノサイト - 書くだけ、Markdown。それがサイトになる。"
  zh: "微站 - 写下 Markdown，就是你的网站。"

siteKeywords:
  default: "static blog, markdown, github pages, blog"
  en: "static blog, markdown, github pages, blog"
  ja: "静态博客, Markdown, GitHub Pages, 博客"
  zh: "静的ブログ, Markdown, GitHub Pages, ブログ"

avatar: assets/avatar.jpeg

contentRoot: wwwroot

contentOutdatedDays: 180

cardCoverFallback: false

errorOverlay: true

pageSize: 8

defaultLanguage: en

themeMode: user

themePack: arcus

themeOverride: false

showAllPosts: true

landingTab: About

repo:
  owner: deemoe404
  name: NanoSite
  branch: doc

assetWarnings:
  largeImage:
    enabled: true
    thresholdKB: 500
