# yaml-language-server: $schema=./assets/schema/site.json

siteTitle:
  default: NanoSite
  en: NanoSite
  ja: "ナノサイト"
  zh: "微站"

siteSubtitle:
  default: "Just Markdown. Just a website."
  en: "Just Markdown. Just a website."
  ja: "書くだけ、Markdown。それがサイトになる。"
  zh: "写下 Markdown，就是你的网站。"

siteDescription:
  default: "NanoSite - Just Markdown. Just a website."
  ja: "ナノサイト - 書くだけ、Markdown。それがサイトになる。"
  zh: "微站 - 写下 Markdown，就是你的网站。"

siteKeywords: "static blog, markdown, github pages, blog"

avatar: assets/avatar.jpeg

profileLinks:
  -
    label: GitHub
    href: "https://github.com/deemoe404/NanoSite"
  -
    label: Demo
    href: "https://deemoe404.github.io/NanoSite"

contentRoot: wwwroot

contentOutdatedDays: 180

cardCoverFallback: false

errorOverlay: true

pageSize: 8

defaultLanguage: en

themeMode: user

themePack: native

themeOverride: true

showAllPosts: true

landingTab: About

repo:
  owner: deemoe404
  name: NanoSite
  branch: doc

assetWarnings:
  largeImage:
    enabled: true
    thresholdKB: 500
