# yaml-language-server: $schema=./assets/schema/site.json

# Site identity configurations
siteTitle:
  default: NanoSite
  zh: 微站
  ja: ナノサイト
siteSubtitle:
  default: Just Markdown. Just a website.
  zh: 写下 Markdown，就是你的网站。
  ja: 書くだけ、Markdown。それがサイトになる。
avatar: assets/avatar.jpeg

# Social media links
profileLinks:
  - label: GitHub
    href: https://github.com/deemoe404/NanoSite
  - label: Demo
    href: https://nano.dee.moe/

# SEO optimization configurations
resourceURL: https://nano.dee.moe/wwwroot/
siteDescription:
  default: NanoSite - Just Markdown. Just a website.
  zh: 微站 - 写下 Markdown，就是你的网站。
  ja: ナノサイト - 書くだけ、Markdown。それがサイトになる。
siteKeywords:
  default: static blog, markdown, github pages, blog

# Miscellaneous configurations
contentOutdatedDays: 180  # Days before content is considered outdated
cardCoverFallback: false  # Use a generated fallback cover image if none provided
errorOverlay: true        # Show error overlay on the page if an error occurs
pageSize: 2               # Number of posts per page on the index list
defaultLanguage: en       # Default UI/content language (e.g., en, zh, ja)

# Theme override configurations
themeMode: user
themePack: minimalism
themeOverride: true

# Asset warnings configurations
assetWarnings:
  largeImage:
    enabled: true
    thresholdKB: 500
