# yaml-language-server: $schema=./assets/schema/site.json

# Site identity configurations
siteTitle:
  default: Yet-another NanoSite
  en: Yet-another NanoSite
  zh: 世界上的另一个微站
  ja: もうひとつのナノサイト
siteSubtitle:
  default: Just Markdown. Just a website.
  en: Just Markdown. Just a website.
  zh: 写下 Markdown，就是你的网站。
  ja: 書くだけ、Markdown。それがサイトになる。
avatar: assets/avatar.jpeg

# Social media links
profileLinks:
  - label: demo
    href: https://deemoe404.github.io/NanoSite/

# SEO optimization configurations
# resourceURL: https://deemoe404.github.io/NanoSite/wwwroot/
# siteDescription:
#   default: NanoSite - Just Markdown. Just a website.
#   zh: 微站 - 写下 Markdown，就是你的网站。
#   ja: ナノサイト - 書くだけ、Markdown。それがサイトになる。
# siteKeywords:
#   default: static blog, markdown, github pages, blog

# Miscellaneous configurations
contentOutdatedDays: 180  # Days before content is considered outdated
cardCoverFallback: false  # Use a generated fallback cover image if none provided
errorOverlay: true        # Show error overlay on the page if an error occurs
pageSize: 8               # Number of posts per page on the index list
defaultLanguage: en       # Default UI/content language (e.g., en, zh, ja)
contentRoot: wwwroot      # Root directory for content files

# Theme override configurations
themeMode: user
themePack: native
themeOverride: true

# Repository information used for internal linking of "report issue" etc.
# repo:
#   owner: deemoe404
#   name: NanoSite
#   branch: main

# Asset warnings configurations
assetWarnings:
  largeImage:
    enabled: true
    thresholdKB: 500

# landingTab: About   # Set to a tab slug or title defined in tabs.yaml
# showAllPosts: true  # Set to false to hide the All Posts tab/index
